vim.opt.list          = true
vim.opt.listchars     = "space:·,tab:-> "

vim.opt.autoindent    = true
vim.opt.backup        = false
--vim.opt.backupdir       = cache_dir
vim.opt.cc            = "80"
vim.opt.clipboard     = "unnamedplus"
vim.opt.cursorline    = true
vim.opt.expandtab     = true
vim.opt.ignorecase    = true
vim.opt.inccommand    = "nosplit"
vim.opt.nu            = true
vim.opt.rnu           = true
vim.opt.hlsearch      = true
vim.opt.incsearch     = true
vim.opt.mouse         = "a"
vim.opt.shiftwidth    = 4
vim.opt.showmatch     = true
vim.opt.showmode      = false
vim.opt.signcolumn    = "yes"
vim.opt.spell         = false
vim.opt.splitbelow    = true
vim.opt.splitright    = true
vim.opt.tabstop       = 4
vim.opt.termguicolors = true
vim.opt.ttyfast       = true
vim.opt.updatetime    = 300
vim.opt.wildmode      = { 'longest', 'list' }
vim.opt.writebackup   = false
