if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done

    unset f
fi

exec_once()
{
    if command -v $1 >/dev/null; then
        pgrep -u $USER $1 || $@ &
    fi
}

exec_once /usr/lib/xdg-desktop-portal-gtk
unset exec_once

exec /usr/local/bin/dwm
