monitor=,preferred,auto,auto

$alts = ALT
$mods = SUPER
$shft = SHIFT

$terminal = kitty
$fileManager = thunar
$menu = wofi --show drun

env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt5ct

source = ~/.config/hypr/hyprland/animations.conf
source = ~/.config/hypr/hyprland/autostart.conf
source = ~/.config/hypr/hyprland/decoration.conf
source = ~/.config/hypr/hyprland/general.conf
source = ~/.config/hypr/hyprland/gestures.conf
source = ~/.config/hypr/hyprland/input.conf
source = ~/.config/hypr/hyprland/keybinds.conf
source = ~/.config/hypr/hyprland/misc.conf
source = ~/.config/hypr/hyprland/windowrules.conf

dwindle {
    # master switch for pseudotiling. Enabling is bound to mainMod + P
    # in the keybinds section
    pseudotile = true

    # you probably want this
    preserve_split = true
}

master {
    new_is_master = true
}
