# See https://wiki.hyprland.org/Configuring/Keywords/ for more
$AltKey = ALT
$CtlKey = CTRL
$ModKey = SUPER
$ShfKey = SHIFT

# Hyprland Binds
bind = $ModKey $ShfKey,         Q,      exit

# Default Apps
bind = $ModKey,            Return,      exec,       kitty
bind = $ModKey,                 B,      exec,       firefox
bind = $ModKey,                 R,      exec,       wofi --show run
bind = $ModKey $ShfKey,         R,      exec,       wofi --show drun
bind = $AltKey,                 M,      exec,       audacious

# Audacious Music Player
bind =, XF86AudioPlay,       exec,      audacious -t
bind =, XF86AudioNext,       exec,      audacious -f
bind =, XF86AudioPrev,       exec,      audacious -r

# Sound Management
bindel=, XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%+
bindel=, XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%-
bindl =, XF86AudioMute,        exec, wpctl set-mute   @DEFAULT_AUDIO_SINK@ toggle

# Window Management
bind = $ModKey $ShfKey,         C,      killactive
bind = $CtlKey $ModKey,     Space,      togglefloating
bind = $ModKey,                 M,      fullscreen, 1
bind = $ModKey,                 F,      fullscreen

# Move focus with ModKey + arrow keys
bind = $ModKey,              left,      movefocus, l
bind = $ModKey,             right,      movefocus, r
bind = $ModKey,                up,      movefocus, u
bind = $ModKey,              down,      movefocus, d
#bind = $ModKey, P, pseudo, # dwindle
#bind = $ModKey, J, togglesplit, # dwindle


# Switch workspaces with ModKey + [0-9]
bind = $ModKey, 				1,		workspace, 1
bind = $ModKey, 				2,		workspace, 2
bind = $ModKey, 				3,		workspace, 3
bind = $ModKey, 				4,		workspace, 4
bind = $ModKey, 				5,		workspace, 5
bind = $ModKey, 				6,		workspace, 6
bind = $ModKey, 				7,		workspace, 7
bind = $ModKey, 				8,		workspace, 8
bind = $ModKey, 				9,		workspace, 9
bind = $ModKey, 				0,		workspace, 10

# Move active window to a workspace with ModKey + SHIFT + [0-9]
bind = $ModKey $ShfKey, 		1,		movetoworkspace, 1
bind = $ModKey $ShfKey, 		2,		movetoworkspace, 2
bind = $ModKey $ShfKey, 		3,		movetoworkspace, 3
bind = $ModKey $ShfKey, 		4,		movetoworkspace, 4
bind = $ModKey $ShfKey, 		5,		movetoworkspace, 5
bind = $ModKey $ShfKey, 		6,		movetoworkspace, 6
bind = $ModKey $ShfKey, 		7,		movetoworkspace, 7
bind = $ModKey $ShfKey, 		8,		movetoworkspace, 8
bind = $ModKey $ShfKey, 		9,		movetoworkspace, 9
bind = $ModKey $ShfKey, 		0,		movetoworkspace, 10

# Scroll through existing workspaces with ModKey + scroll
bind = $ModKey,        mouse_down,      workspace, e+1
bind = $ModKey,          mouse_up,      workspace, e-1

# Move/resize windows with ModKey + LMB/RMB and dragging
bindm = $ModKey,        mouse:272,      movewindow
bindm = $ModKey,        mouse:273,      resizewindow
