# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

windowrule = workspace 1, firefox
windowrule = workspace 2, kitty
windowrule = workspace 3, (Audacious)$

windowrule = maximize, firefox
