exec-once = ~/.config/hypr/hyprland_scripts/xdg-desktop-portal-hyprland.sh &

# exec-once = hyprpaper &
exec-once = mako &
exec-once = waybar --config ~/.config/hypr/waybar.jsonc &
exec-once = wl-paste --type text  --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
