local Plug = vim.fn['plug#']

vim.call('plug#begin', '~/.config/nvim/plugged')
    Plug('andweeb/presence.nvim')
    Plug('BurntSushi/ripgrep')
    Plug('HiPhish/nvim-ts-rainbow2')
    Plug('mhinz/vim-startify')
    Plug('neoclide/coc.nvim', { branch = 'release', ['do'] = ':CocUpdate' })
    Plug('nvim-lua/plenary.nvim')
    Plug('nvim-lualine/lualine.nvim')
    Plug('nvim-telescope/telescope.nvim', { branch = '0.1.x' })
    Plug('nvim-telescope/telescope-fzf-native.nvim')
    Plug('nvim-tree/nvim-tree.lua')
    Plug('nvim-tree/nvim-web-devicons')
    Plug('nvim-treesitter/nvim-treesitter', { ['do'] = ':TSUpdate' })
    Plug('nvim-treesitter/nvim-treesitter-textobjects')
    Plug('preservim/nerdcommenter')
    Plug('tomasr/molokai')
vim.call('plug#end')
