local Plug = vim.fn['plug#']

vim.call('plug#begin', '~/.config/nvim/plugged')
    -- Plug('dracula/vim')
    -- Plug('honza/vim-snippets')
    -- Plug('SirVer/ultisnips')
    Plug('andweeb/presence.nvim')
    Plug('HiPhish/nvim-ts-rainbow2')
    Plug('mhinz/vim-startify')
    Plug('preservim/nerdcommenter')
    Plug('neoclide/coc.nvim', { branch = 'master', ['do'] = 'yarn install --frozen-lockfile' })
    Plug('nvim-treesitter/nvim-treesitter', { ['do'] = ':TSUpdate' })
    Plug('ryanoasis/vim-devicons')
    Plug('scrooloose/nerdtree', { on = 'NERDTreeToggle' })
    Plug('tomasr/molokai')
vim.call('plug#end')
